Use uid's instead of patient/sample ids
cBioPortal/iViz pull request #474
Opened 2017-04-25 23:52 UTC by kalletlak

Fix #150

2017-04-26 15:22 UTC, zhx828 commented on app/scripts/main.js
> +    getcaseUIDs: function(type) {
Should be named as getCaseUIDs

2017-04-26 15:25 UTC, zhx828 commented
@kalletlak  in the new changes, if you use rainbow survival plot to draw clinical attribute `CN Cluster` the DFS survival doesn't show anything. When I try to debug, the DFS has been included into `sample` group for some reason. I will continue debugging. And should this go to `master` branch?

2017-04-26 15:32 UTC, kalletlak commented
Yes, it is to `master` branch

2017-04-27 15:35 UTC, yichaoS approved these changes

2017-04-28 18:19 UTC, zhx828 requested changes
Done the code review. Before merging, I need to do end-to-end tests. Please wait

2017-04-28 18:19 UTC, zhx828 commented on app/scripts/vueCore.js
> +                        self_.customfilter.sampleIds = selectedCaseUIDs;
In there, what do we use? uid or id? If uid, shouldn't we change the key to sampleUids in customfilter as well? A little confused here.

2017-04-28 18:19 UTC, zhx828 commented on app/scripts/model/dataProxy.js
> +              var sample_to_patient_uid = {};
This name is a little misleading. I suggest using `sample_uid_to_patient_uid `

2017-04-28 18:19 UTC, zhx828 commented on app/scripts/model/dataProxy.js
> +                  has_attr_data: _hasSampleAttrData
How do we decide the naming convention here?

2017-04-28 18:19 UTC, zhx828 commented on app/scripts/model/dataProxy.js
> -                self.getSampleClinicalData(_.keys(_sampleAttributes)),
We no longer caching the full data any more?

2017-04-28 18:19 UTC, zhx828 commented on app/scripts/model/dataProxy.js
> +                    studyCaseList.cnaSampleIds = self.data.sampleLists.cna[cancer_study_id];
self.data.sampleLists.cna may not be initialized. This will throw exception

2017-04-28 18:19 UTC, zhx828 commented on app/scripts/main.js
> +      function getAttrVal(attrs, arr) {
We don't nest function inside function. Maybe put into util?

2017-04-28 18:19 UTC, zhx828 commented on app/scripts/model/dataProxy.js
> +                    studyCaseList.allSampleIds = self.data.sampleLists.all[cancer_study_id];
This needs to be sorted. Please check left panel to make sure all lists are sorted

2017-05-01 15:39 UTC, kalletlak commented on app/scripts/vueCore.js
> +                        self_.customfilter.sampleIds = selectedCaseUIDs;
Yes, it should be with `Uids`. I'll update it

2017-05-01 15:39 UTC, kalletlak commented on app/scripts/model/dataProxy.js
> +                  has_attr_data: _hasSampleAttrData
I'll change it to _`sampleData` and `_patientData`

2017-05-01 15:47 UTC, kalletlak commented on app/scripts/model/dataProxy.js
> +                    studyCaseList.cnaSampleIds = self.data.sampleLists.cna[cancer_study_id];
its initialized at line
https://github.com/cBioPortal/iViz/blob/master/app/scripts/model/dataProxy.js#L969

2017-05-01 15:49 UTC, kalletlak commented on app/scripts/model/dataProxy.js
> +                    studyCaseList.allSampleIds = self.data.sampleLists.all[cancer_study_id];
this new logic is completely different. I am not concatenating samples

2017-05-01 15:51 UTC, kalletlak commented on app/scripts/model/dataProxy.js
> +              var sample_to_patient_uid = {};
Sure, will change that

2017-05-01 16:00 UTC, kalletlak commented on app/scripts/model/dataProxy.js
> -                self.getSampleClinicalData(_.keys(_sampleAttributes)),
`sampleInitData and patientInitData` clinical data are never used here. And is seems like we are trying to cache data for all clinical attribute with isn't required at this point.

2017-05-01 16:05 UTC, kalletlak commented on app/scripts/main.js
> +      function getAttrVal(attrs, arr) {
Sure!

2017-05-02 20:53 UTC, zhx828 approved these changes

2017-05-02 20:55 UTC, zhx828 commented
All public studies passed end-to-end test

2017-05-17 21:47 UTC, zhx828 commented
@kalletlak The numbers in the header are not changing after selecting few genes.

![screen shot 2017-05-17 at 5 45 57 pm](https://cloud.githubusercontent.com/assets/5400599/26177697/c7160756-3b28-11e7-9016-78f529d9415c.png)

2017-05-19 16:42 UTC, merged