Scientific log for small numbers
cBioPortal/iViz pull request #522
Opened 2017-06-07 21:24 UTC by victoria34

Add minExponent and maxExponent. Check if data of getDecimalExponents is empty.

2017-06-20 17:11 UTC, zhx828 requested changes

2017-06-20 17:11 UTC, zhx828 commented on app/_components/cbio-util.js
> +    if (data === null || data.length < 1) {//if data is null or empty, return data
You should use `_.isArray(data)` instead of `data === null`

2017-06-20 17:11 UTC, zhx828 commented on app/_components/cbio-util.js
> +    values.sort(function(a, b) {
The default sorting is a-b. You should use `values.sort()` directly

2017-06-20 17:11 UTC, zhx828 commented on app/_components/cbio-util.js
> +    while (values[0] < 1) {
Like I said before, `values` is not guaranteed to have any elements

2017-06-20 17:11 UTC, zhx828 commented on app/scripts/views/components/barChart/barChart.js
> +      } else if (data_.smallDataFlag) {
Can't this part be merged with line 115-120?

2017-06-20 17:11 UTC, zhx828 commented on app/scripts/views/components/barChart/barChart.js
> +        if (data_.smallDataFlag) {
This part should be merged with line 165

2017-06-20 17:11 UTC, zhx828 commented on app/scripts/views/components/barChart/barChart.js
> +            config.divider = 8;
Is the divider 8 sufficient enough if exponentRange is 100?

2017-06-22 18:26 UTC, victoria34 commented on app/_components/cbio-util.js
> +    values.sort(function(a, b) {
The default sort() should return values from small numbers to large values. But in here, it works conversely, so I have to write 'a-b'.

2017-06-22 19:05 UTC, victoria34 commented on app/scripts/views/components/barChart/barChart.js
> +      } else if (data_.smallDataFlag) {
I'm afraid not. Line 115-120 uses linear() scale, but scientific numbers use log() scale.

2017-06-22 19:07 UTC, victoria34 commented on app/_components/cbio-util.js
> +    if (data === null || data.length < 1) {//if data is null or empty, return data
Good Idea. Thanks!

2017-06-22 19:12 UTC, victoria34 commented on app/scripts/views/components/barChart/barChart.js
> +        if (data_.smallDataFlag) {
var e = d3.format('.1e');// convert small data to scientific notation format
For scientific numbers, they should be covert to scientific format by e(). If I merged them, normal numbers will also show in scientific format.

2017-06-22 19:13 UTC, victoria34 commented on app/_components/cbio-util.js
> +    while (values[0] < 1) {
You're right. I will use a for loop to make sure min and max values are valid numbers.

2017-06-22 19:24 UTC, zhx828 commented on app/_components/cbio-util.js
> +    values.sort(function(a, b) {
a-b is from small to large values

2017-06-22 19:26 UTC, zhx828 commented on app/scripts/views/components/barChart/barChart.js
> +      } else if (data_.smallDataFlag) {
sorry 106-107

2017-06-22 19:28 UTC, zhx828 commented on app/scripts/views/components/barChart/barChart.js
> +        if (data_.smallDataFlag) {
You still need the if condition, but parts `return '>' + ` and `opts_.xDomain[opts_.xDomain.length - 3]` are the same

2017-06-22 20:07 UTC, victoria34 commented on app/scripts/views/components/barChart/barChart.js
> +            config.divider = 8;
if (data.smallDataFlag) {
          var numberOfTickValues = 4;
          config.divider = Math.round(exponentRange / numberOfTickValues);
}
Now config.divider is calculated automatically.

2017-06-22 20:37 UTC, victoria34 commented on app/_components/cbio-util.js
> +    values.sort(function(a, b) {
I didn't explain clearly. Values.sort() in here return data based on kind of alphabetical order, so I have to mention I want to sort data in ascending order.

2017-06-22 20:43 UTC, victoria34 commented on app/scripts/views/components/barChart/barChart.js
> +      } else if (data_.smallDataFlag) {
if (logScale || data_.smallDataFlag) {
        chartInst_.x(d3.scale.log().nice()
          .domain([opts_.minDomain, opts_.maxDomain]));
 }
Sure, I haved merged them.

2017-06-22 20:51 UTC, victoria34 commented on app/scripts/views/components/barChart/barChart.js
> +        if (data_.smallDataFlag) {
formattedValue = opts_.xDomain[1];
        if (data_.smallDataFlag) {
          return '<=' + e(formattedValue);
        }
        return '<=' + formattedValue;

2017-07-11 22:26 UTC, closed without merging