Solved single value in data and breadcrumb range issues
cBioPortal/iViz pull request #544
Opened 2017-07-06 19:46 UTC by victoria34

2017-07-13 17:25 UTC, zhx828 requested changes
I need to talk about lines 163-258 in barChartTemplate.js

2017-07-13 17:25 UTC, zhx828 commented on app/_components/cbio-util.js
> +      if ($.isNumeric(values[head])) {
No need to check  isNumeric any more. It has been down in line 688-689

2017-07-13 17:25 UTC, zhx828 commented on app/_components/cbio-util.js
> +      if ($.isNumeric(values[head])) {
Same here

2017-07-13 17:25 UTC, zhx828 commented on app/scripts/views/components/barChart/barChart.js
> +          } else if (d[data_.attrId] > opts_.xDomain[opts_.xDomain.length - 3]) {
Do we do checking on xDomain lenght?

2017-07-13 20:43 UTC, victoria34 commented on app/scripts/views/components/barChart/barChart.js
> +          } else if (d[data_.attrId] > opts_.xDomain[opts_.xDomain.length - 3]) {
I think we check xDomain.length in function getTickFormat.

2017-07-13 20:44 UTC, victoria34 commented on app/_components/cbio-util.js
> +      if ($.isNumeric(values[head])) {
I will remove it.

2017-07-13 20:44 UTC, victoria34 commented on app/_components/cbio-util.js
> +      if ($.isNumeric(values[head])) {
I will remove it.

2017-07-27 18:46 UTC, zhx828 commented on app/scripts/views/components/barChart/barChartTemplate.js
> +        if (typeof d === 'undefined' || d === 'na' || d === '' ||
Use `iViz.util.strIsNa(d, true)` here

2017-07-27 19:29 UTC, zhx828 requested changes

2017-07-27 19:29 UTC, zhx828 commented on app/scripts/views/components/barChart/barChartTemplate.js
> +        this.data.valueAsTick = false;
Can we change this variable name? I don't understand it until I come here

2017-07-27 19:29 UTC, zhx828 commented on app/scripts/views/components/barChart/barChart.js
> +            } else if (!data_.valueAsTick) {
What happened if data.smaillDataFlag is true, and data_.valueAsTick is true as well?

2017-08-01 13:19 UTC, merged