Fixed CancerType/CancerTypeDetails tables hang after interaction
cBioPortal/iViz pull request #549
Opened 2017-07-11 18:39 UTC by victoria34

2017-07-11 22:06 UTC, zhx828 requested changes
Please remove unnecessary variables and functions. Thanks.

2017-07-11 23:10 UTC, zhx828 requested changes

2017-07-11 23:10 UTC, zhx828 commented on app/scripts/views/components/dataTable/tableViewTemplate.js
> +            if (this.dataLoaded) {
This should be included with the else statement above

2017-07-11 23:10 UTC, zhx828 commented on app/scripts/views/components/dataTable/tableViewTemplate.js
> +        if (this.selectedRows) {
The condition should be decided based on `_selectedCases`

2017-07-12 15:00 UTC, victoria34 commented on app/scripts/views/components/dataTable/tableViewTemplate.js
> +        if (this.selectedRows) {
I have changed it to if (_selectedCases.length > 0). Thanks!

2017-07-12 15:02 UTC, victoria34 commented on app/scripts/views/components/dataTable/tableViewTemplate.js
> +            if (this.dataLoaded) {
if (!this.failedToInit) {
          if (this.madeSelection && !this.isMutatedGeneCna) {
            this.madeSelection = false;
          } else if (this.dataLoaded) {
            var attrId =
              this.attributes.group_type === 'patient' ?
                'patient_uid' : 'sample_uid';
            var _selectedCases =
              _.pluck(this.invisibleDimension.top(Infinity), attrId);
            this.chartInst.update(_selectedCases, this.selectedRows);
            this.setDisplayTitle(this.chartInst.getCases().length);
            this.showLoad = false;
            this.showRainbowSurvival();
          }
    }

2017-07-12 22:19 UTC, zhx828 approved these changes

2017-07-12 22:19 UTC, merged

2017-07-24 22:41 UTC, zhx828 commented
This closes #445