Fixed special characters in Number.
cBioPortal/iViz pull request #552
Opened 2017-07-12 22:31 UTC by victoria34

2017-07-21 21:03 UTC, zhx828 requested changes

2017-07-21 21:03 UTC, zhx828 commented on app/scripts/views/components/barChart/barChart.js
> +        if (strVal.includes('<')) {
lines 26-36 have similar patterns. They can be consolidated together.

2017-07-21 21:03 UTC, zhx828 commented on app/scripts/views/components/barChart/barChartTemplate.js
> +          if (number.includes('<')) {
Same here

2017-07-24 17:45 UTC, victoria34 commented on app/scripts/views/components/barChart/barChart.js
> +        if (strVal.includes('<')) {
I removed them since we only send max and min to barChart.js

2017-07-24 17:46 UTC, victoria34 commented on app/scripts/views/components/barChart/barChartTemplate.js
> +          if (number.includes('<')) {
if (number.includes('<=')) {
            smallerOutlier.push(number.slice(2));
          } else if (number.includes('<') && !number.includes('<=')) {
            smallerOutlier.push(number.slice(1));
          } else if (number.includes('>=')) {
            greaterOutlier.push(number.slice(2));
          } else if (number.includes('>') && !number.includes('>=')) {
            greaterOutlier.push(number.slice(1));
          }

2017-07-24 20:21 UTC, zhx828 requested changes

2017-07-24 20:21 UTC, zhx828 commented on app/scripts/views/components/barChart/barChart.js
> +        if (typeof val === 'undefined' || val === 'NA' || val === '' ||
Why not use ` iViz.util.strIsNa`?

2017-07-24 20:21 UTC, zhx828 commented on app/scripts/views/components/barChart/barChartTemplate.js
> +        if (typeof d === 'undefined' || d === 'na' || d === '' ||
Same here, we should use ` iViz.util.strIsNa` and few special cases

2017-07-24 20:21 UTC, zhx828 commented on app/scripts/views/components/barChart/barChartTemplate.js
> +          } else if (number.includes('<') && !number.includes('<=')) {
No need to check `number.includes('<=')` any more, same to line 211

2017-07-24 20:21 UTC, zhx828 commented on app/scripts/views/components/barChart/barChartTemplate.js
> +            smallerOutlier.push(number.slice(1));
Data is not always <123, it could be 123<

2017-07-24 20:21 UTC, zhx828 commented on app/scripts/views/components/barChart/barChartTemplate.js
> +          if (number.includes('<=')) {
You should think about how to combine these conditions together. A regular expression could be useful with index.

2017-07-24 21:04 UTC, victoria34 commented on app/scripts/views/components/barChart/barChartTemplate.js
> +          if (number.includes('<=')) {
if (number.includes('<')) {
            smallerOutlier.push(number.replace(/[^0-9.]/g, ""));
          } else if (number.includes('>')) {
            greaterOutlier.push(number.replace(/[^0-9.]/g, ""));
          } else {
            _dataIssue = true;
          }

2017-07-26 20:13 UTC, zhx828 commented on app/scripts/views/components/barChart/barChart.js
> +        if (iViz.util.strIsNa(val, true) || isNaN(val)) {
Doesn't `iViz.util.strIsNa(val, true)` cover isNaN check already?

2017-07-26 20:13 UTC, zhx828 commented on app/scripts/views/components/barChart/barChartTemplate.js
> +        var smallerOutlierPattern = new RegExp('^<|(>=|>)$');
Or `^<|(>=?)$`

2017-07-26 21:44 UTC, victoria34 commented on app/scripts/views/components/barChart/barChartTemplate.js
> +        var smallerOutlierPattern = new RegExp('^<|(>=|>)$');
This is clearer. Thanks!

2017-07-27 16:56 UTC, zhx828 approved these changes

2017-07-27 16:57 UTC, merged