Async mutation count bar chart & breadcrumb format
cBioPortal/iViz pull request #579
Opened 2017-08-08 23:09 UTC by victoria34

Make mutation_count bar chart async.
Add hasNA for "NA" value and modify gutter when noGrouping is true. 
Create empty chart when mutation_count data is null. 
Reset tick format about NA. 
Change breadcrumb format. 
Add getMutationCountData() and avoid duplicate charts in updateDataObject().

2017-08-09 21:32 UTC, zhx828 requested changes

2017-08-09 21:32 UTC, zhx828 commented on app/scripts/main.js
> +          var _hasMutationCountData = _mutationCountResult[1];
`_hasMutationCountData` should have a default value? In case, _mutationCountResult is not array or for some reason `self. getMutationCountData ` failed?

2017-08-10 16:27 UTC, victoria34 commented on app/scripts/main.js
> +          var _hasMutationCountData = _mutationCountResult[1];
Good idea! I will change it. Thanks!

2017-08-10 18:57 UTC, zhx828 requested changes

2017-08-10 18:57 UTC, zhx828 commented on app/scripts/main.js
> +          if (_mutationCountResult[1]) {
If `_mutationCountResult ` is not array, it will throw error here

2017-08-10 18:57 UTC, zhx828 commented on app/scripts/views/components/barChart/barChartTemplate.js
> +    'style="float:none !important;" id={{chartId}} >' +
Why introduce a `important`?

2017-08-10 18:57 UTC, zhx828 commented on app/scripts/views/components/scatterPlot/scatterPlotTemplate.js
> +              _self.attributes.show = false;
Even when added by default, the errorMessage.noData and failedToInit should be set to true as well?

2017-08-11 19:09 UTC, victoria34 commented on app/scripts/views/components/scatterPlot/scatterPlotTemplate.js
> +              _self.attributes.show = false;
Changed

2017-08-14 14:03 UTC, zhx828 approved these changes

2017-08-14 14:04 UTC, merged